### PR TITLE
change SS.py

### PR DESCRIPTION
**Pull request by miltonash**
small changes needed for `test_SS` including:
. remove unnecessary w_init from `solve_ss` arguments
. add ss_iter to the return line for use in the assertion within `test_SS.py`

### CODE REVIEW

**Comment by miltonash** [comment]
I resolved the conflicts and pushed a new commit to this branch, but it's not showing up here. Any idea why that might be?

**Comment by LeiliPR** [comment]
I can see the scripts and changes that you have made.

**Comment by saharnazb** [comment]
That's weird. I can see other changes but not the test. Maybe you need to commit again.

**Comment by saharnazb** [comment]
I cannot see the test_SS.py in your own github fork too. Look if the file is in the right place

**Comment by LeiliPR** [comment]
oh, I cant see the test as well, make sure you have it in your local branch.

**Comment by miltonash** [comment]
@saharnazb - Because Jet had an open pull request for `test_SS.py`, I thought it would easier to give him our work instead of creating a new pull request for the same file name. I posted our code under his pull request as a comment.

**Comment by saharnazb** [comment]
@miltonash So close this one

**Comment by miltonash** [comment]
@saharnazb I think I need @jdebacker to merge this pull request, since it contains minor changes to `SS.py` that will be necessary for `test_SS.py` happening in another pull request.

**Comment by jdebacker** [comment]
Ok - merging.

**Pull request merged**
