### PR TITLE
Modified test

### PR DESCRIPTION
**Pull request by adibalaram**
Checking if it passes the test after modified the test file.

### CODE REVIEW

**Comment by adibalaram** [comment]
@jdebacker I can't figure out what's going on here.

**Comment by jdebacker** [comment]
@adibalaram I'm not sure what your question is, but my guess is that you are referring to the tests failing.  

To see the tests failing you can:
1. Run them locally from the `.scripts` directory: `python -m pytest` and you will see some tracebacks to help you identify the tests that fail and why.
2. You can see that same output from the tests run on Travis CI by clicking the "Details" link by the "Build Failed" line and then on the next paid, click on the run number (e.g. Job "88.2").

I see 3 tests failing now:
1. `FOC_labor` - not sure why, but not getting the value back I'd expect for the error given that an unused argument was removed.  Could it be something was out of order?
2. `FOC_save` - test not accounting for new number of arguments.
3. `FOCs` - now computes BQ within function...

I'll be offline until morning.

**Comment by jdebacker** [comment]
@adibalaram I think I've fixed your issues (at least the tests are passing and I think the HH functions and the `get_BQ` are good.  I added an argument to `households.FOCs` and to `get_BQ` so that the same functions can handle the SS and the time path solutions.

**Comment by jdebacker** [comment]
I'll go ahead and merge this and then people can start trying to solve the SS based on these household functions.

**Pull request merged**
